name: Deploy

on:
  push:
    branches: [ 'main' ]

jobs:
  deploy:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: docker
        uses: whoan/docker-build-with-cache-action@v5
        with:
          username: custody
          password: "${{ secrets.GITHUB_TOKEN }}"
          registry: docker.pkg.github.com
          image_name: custody/slate
      - name: run deploy.sh
        id: run-deploy
        run: ./deploy.sh
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
